### ISSUE TITLE
Warning on boot (deprecated API)

### ISSUE THREAD

**Issue by marcoskirsch** [marcoskirsch/nodemcu-httpserver#103]
`Warning, deprecated API! Argument style station configuration is replaced by table style station configuration. It will be removed in the next version. See documentation for details.
`

Needs to be updated.

**Comment by Godzil** [comment]
The bug fix missed the SoftAP wifi.ap.setip that also want a table and not just the IP in a string. Maybe a full pass on the wifi api should be done.

I will prepare a PR for wifi.ap.setip
