### ISSUE TITLE
args.lua saved to disk instead of opening in browser

### ISSUE THREAD

**Issue by choncba** [marcoskirsch/nodemcu-httpserver#11]
Hi, in the example, when I enter to a index.html from a web browser, and then click on link to a .lua (ie arguments link), the browser want to download the arguments.lua instead of open a new window with the html content, Why?

Thank you, awesome job!

**Comment by marcoskirsch** [comment]
I would guess is due to a malformed HTTP header being sent by the script or a bad MIME type.
What browser are you using? Have you tried others?

**Comment by choncba** [comment]
Thanks for the reply, I'm using Firefox on Linux mint, I'll try chrome. I notice if it works.

UPDATE: Solved! It works fine in chrome and ie. Thank you!
