### ISSUE TITLE
Compiling:      httpserver-conf.lua

### ISSUE THREAD

**Issue by jpmorrison** [marcoskirsch/nodemcu-httpserver#110]
Flashed:
NodeMCU custom build by frightanic.com
        branch: master
        commit: 2e67ff5a639a13260fd4fb3c3b627ccdc2845616
        SSL: true
        modules: adc,ads1115,bit,ds18b20,enduser_setup,file,gpio,i2c,mdns,mqtt,net,node,ow,pwm,sntp,spi,struct,tmr,uart,websocket,wifi,tls
 build  built on: 2017-08-30 18:00
 powered by Lua 5.1.4 on SDK 2.1.0(116b762)

upload with make and get this error:

Compiling:      httpserver-conf.lua
lua: httpserver-conf.lua:25: unexpected symbol near '}'
stack traceback:
        [C]: in function 'compile'
        ?: in function <?:5>
        ?: in main chunk
        [C]: in function 'dofile'
        init.lua:3: in main chunk
        [C]: ?

it compiles if I remove the brace

**Comment by marcoskirsch** [comment]
Fixed #107
