### ISSUE TITLE
Jquery zipped file is too large

### ISSUE THREAD

**Issue by marcoskirsch** [marcoskirsch/nodemcu-httpserver#16]
There's an example in the http/ folder for testing out serving compressed file. But the file we are demoing with is too large. 

We should replace with something smaller so that all the files fit into flash well.

**Comment by marcoskirsch** [comment]
Fixed https://github.com/marcoskirsch/nodemcu-httpserver/commit/0cc7a8b7be184c4e59914760744bb20a371447d7

**Comment by flip111** [comment]
To make it even smaller ... http://zeptojs.com/
