### ISSUE TITLE
WiFi configuration is not ready to operate as AP only

### ISSUE THREAD

**Issue by pospanet** [marcoskirsch/nodemcu-httpserver#30]
init.lua is not ready to set wifi mode to AP only. IP setting is missing at all and init is forced to get IP as client, otherwise http server will not start

**Comment by marcoskirsch** [comment]
What you say is correct. init.lua bundled with the server is meant to be edited to suit the client's need and it just happens to be written so by default it joins an existing network. I don't think it's an issue. Am I missing something?

**Comment by pospanet** [comment]
Hi,
if it is like "to be modified", then yes, you are right.I made some
modification whe roy need to amend "just" WiFi mode and the rest Will be
handled with code. Modification is ready to be merged. I am going to send
pull request and it is up to you to decide if it is useful or not. Thanks.

Pospa

S pozdravem
Jan Pospíšil

-<{Pospa}>-

2015-08-09 16:29 GMT+02:00 Marcos notifications@github.com:
