### ISSUE TITLE
init.lua error

### ISSUE THREAD

**Issue by claudioferrari** [marcoskirsch/nodemcu-httpserver#40]
Hello,

I have this problem after make upload_server:

init.lua:55: cannot open/write to file

I'm using nodemcu_float_0.9.6-dev_20150704.bin.

Any suggestions?
Thanks in advance

**Comment by marcoskirsch** [comment]
Format your flash memory and try again. The file system in NodeMCU is not great about reusing space or running out of space. If that doesn't work, then remove the largest files from the examples folder, like the images, and try again.

Let us know if that helped. Good luck!

**Comment by claudioferrari** [comment]
It seems it doesn't compile files:

```
...
> dofile("httpserver.lc")(80)
cannot open httpserver.lc
....
```

**Comment by marcoskirsch** [comment]
Can you confirm that you formatted and started over?

**Comment by claudioferrari** [comment]
Yes, I have also tried to upload all file manually but still get this error (in Explorer):

```
NodeMCU 0.9.6 build 20150704  powered by Lua 5.1.4
set (mode=3)
AP MAC:     1a:fe:34:9d:ad:af
Client MAC:     18:fe:34:9d:ad:af
chip:   10333615
heap:   24840
Compiling:  httpserver.lua
lua: init.lua:55: cannot open/write to file
```

and if I try to use make upload_http:

```
make upload_http
Preparing esp for transfer.
Transfering args.lua as http/args.lua
Bad chunk response "ANIC: unprotected error in call to Lua API (stdin:6: open a file first)
c_??S?fJS?f?j??

NodeMCU 0.9.6 build 20150704  powered by Lua 5.1.4
set (mode=3)
AP MAC:     1a:fe:34:9d:ad:af
Client MAC:     18:fe:34:9d:ad:af
chip:   10333615
heap:   24840
Compiling:  httpserver.lua
lua: init.lua:55: cannot open/write to file
> " 41:4e:49:43:3a:20:75:6e:70:72:6f:74:65:63:74:65:64:20:65:72:72:6f:72:20:69:6e:20:63:61:6c:6c:20:74:6f:20:4c:75:61:20:41:50:49:20:28:73:74:64:69:6e:3a:36:3a:20:6f:70:65:6e:20:61:20:66:69:6c:65:20:66:69:72:73:74:29:0d:0a:63:5f:c7:c1:10:53:f8:66:4a:53:fa:66:12:c3:6a:ee:d4:0d:0a:0d:0a:4e:6f:64:65:4d:43:55:20:30:2e:39:2e:36:20:62:75:69:6c:64:20:32:30:31:35:30:37:30:34:20:20:70:6f:77:65:72:65:64:20:62:79:20:4c:75:61:20:35:2e:31:2e:34:0d:0a:73:65:74:20:28:6d:6f:64:65:3d:33:29:0d:0a:41:50:20:4d:41:43:3a:20:09:31:61:3a:66:65:3a:33:34:3a:39:64:3a:61:64:3a:61:66:0d:0a:43:6c:69:65:6e:74:20:4d:41:43:3a:20:09:31:38:3a:66:65:3a:33:34:3a:39:64:3a:61:64:3a:61:66:0d:0a:63:68:69:70:3a:20:09:31:30:33:33:33:36:31:35:0d:0a:68:65:61:70:3a:20:09:32:34:38:34:30:0d:0a:43:6f:6d:70:69:6c:69:6e:67:3a:09:68:74:74:70:73:65:72:76:65:72:2e:6c:75:61:0d:0a:6c:75:61:3a:20:69:6e:69:74:2e:6c:75:61:3a:35:35:3a:20:63:61:6e:6e:6f:74:20:6f:70:65:6e:2f:77:72:69:74:65:20:74:6f:20:66:69:6c:65:0d:0a:3e:20
Transfering file_list.lua as http/file_list.lua
Error waiting for esp "recv()
stdin:1: attempt to call global 'recv' (a nil value)
> "
Transfering garage_door_opener.css as http/garage_door_opener.css
Error waiting for esp "recv()
stdin:1: attempt to call global 'recv' (a nil value)
> "
Transfering garage_door_opener.html as http/garage_door_opener.html
Error waiting for esp "recv()
stdin:1: attempt to call global 'recv' (a nil value)
> "
Transfering garage_door_opener.lua as http/garage_door_opener.lua
Error waiting for esp "recv()
stdin:1: attempt to call global 'recv' (a nil value)
> "
Transfering index.html as http/index.html
Error waiting for esp "recv()
stdin:1: attempt to call global 'recv' (a nil value)
> "
Transfering node_info.lua as http/node_info.lua
Error waiting for esp "recv()
stdin:1: attempt to call global 'recv' (a nil value)
> "
Transfering post.lua as http/post.lua
Error waiting for esp "recv()
stdin:1: attempt to call global 'recv' (a nil value)
> "
All done!
```

**Comment by pastukhov** [comment]
Looks like yout spiffs is corrupted. Do file.format() and reupload all the files.

**Comment by claudioferrari** [comment]
Thanks guys, I'm finally able to authenticate but I get 404 - Not Found error or 400 - Bad Request when I try index.html (http://<my-ip>/index.html).

Suggestions?

Thanks

**Comment by marcoskirsch** [comment]
Can you confirm that:

a) the URL you typed in the browser does not have the typo that the URL in the message has and
b) that index.html is uploaded correctly in your ESP
?

**Comment by claudioferrari** [comment]
Hi, I finally had a working system (not yet tested POST request).
I have fixed some "bugs" (return should be the last call otherwise has to be incapsulated into do return something end).

I am trying to modify the code in order to reduce the server charge by using ajax call to functions; next step will be to flash all the stuff in ROM by using spiff (surely you are more skilled on this than me).

If you want send me a private email and I will explain you better what I am doing.

Thanks a lot again, when I will be ready I will put into a public repo.

**Comment by marcoskirsch** [comment]
Closing. @claudioferrari there's much newer server and firmware code now, worth trying again. The firmware guys have improved things so much.
