### ISSUE TITLE
Specific files are not delivered correctly

### ISSUE THREAD

**Issue by ilendemli** [marcoskirsch/nodemcu-httpserver#41]
Some files (f.e. the gif and png images in this package) are not delivered fully to the client.

**Comment by marcoskirsch** [comment]
What version of the firmware are you using?

**Comment by ilendemli** [comment]
i am using 0.9.6 of nodemcu integer

**Comment by marcoskirsch** [comment]
Try latest nodemcu-firmware version with latest nodemcu-httpserver code. This should be working. Let me know if not.
