### ISSUE TITLE
Problems with nodemcu dev built with 1.4.0 SDK

### ISSUE THREAD

**Issue by pjsg** [marcoskirsch/nodemcu-httpserver#42]
It appears that the semantics of connection:send (as used in httpserver-error) has changed in recent builds. In particular, it appears that you can only do one :send before you have to wait for the "sent" event. Subsequent :send calls appear to fail. Not clear what the right solution is.....

**Comment by marcoskirsch** [comment]
I haven't had a chance to try the new versions of the firmware. Sounds like there's some work to be done :(

**Comment by pjsg** [comment]
On 22/11/2015 16:26, Marcos wrote:

> I haven't had a chance to try the new versions of the firmware. Sounds 
> like there's some work to be done :(
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/marcoskirsch/nodemcu-httpserver/issues/42#issuecomment-158800928.
> 
> I did submit a pull request to address it. The fix works for me, but I'm 
> new to Lua so it may not be stylistically correct.

Philip

**Comment by marcoskirsch** [comment]
I am merging fixes for new firmware soon. The server appears to work a lot better now - thanks to you and the rest of the nodemcu-firmware people, not thanks to me :)

**Comment by pastukhov** [comment]
Sounds great!

**Comment by marcoskirsch** [comment]
All pushed, try again!
Thanks.
