### ISSUE TITLE
Hangs after first connection

### ISSUE THREAD

**Issue by bepursuant** [marcoskirsch/nodemcu-httpserver#47]
I formatted my MCU, flashed all these files to it, and changed the configuration so it could connect to my WiFi. It connects successfully, but the first time I try to hit it with any type of request, the console registers the call (below), but the browser just hangs. Any subsequent calls from any other clients are not registered on the MCU or responded to.

```
set (mode=3)
AP MAC:     1a:fe:34:a3:38:47
Client MAC:     18:fe:34:a3:38:47
chip:   10696775
heap:   25144
nodemcu-httpserver running at http://192.168.1.1:80
IP:     192.168.1.242
Requested URI: /
Method: GET

```

I disabled the basicauth and it functions exactly the same - no response of any kind (even status codes or headers) ever makes it back to the browser.

I've been digging through recent pulls a little bit to see if there was something that could cause this, but I haven't seen anything obvious yet. I also checked with a different power supply to make sure it wasn't hanging due to a power issue.

Can anyone confirm this on the latest master branch, or am I just crazy?

**Comment by ilendemli** [comment]
nah, you are not crazy, same happens for me

**Comment by marcoskirsch** [comment]
I suspect nodemcu-httpserver may need some modifications in order to again work out of the box due to changes in the newer nodemcu-firmware, which has had a lot of changes.

What firmware version are you using?

**Comment by bepursuant** [comment]
My module is running 0.9.6... 

Could this be related to https://github.com/nodemcu/nodemcu-firmware/issues/846 ? I see some coroutining in the nodemcu-httpserver code near where we are getting stuck, but I don't fully understand the structure of that piece of the code so I'm not sure...

**Comment by exilaus** [comment]
same here 0.9.6.. last version of firmware tested for this software? 0.9.5 work right?

**Comment by marcoskirsch** [comment]
I think we should get this working with the latest firmware (1.5 SDK based nodemcu-firmware) and not try to get it up and running on such old firmware code anymore. There's been a ton of bug fixes in the firmware.

**Comment by rlust** [comment]
Any progress with getting this to work with newer firmware? I am using 1.4 and it hangs on browser access. This looks like a great platform to build on if I could get it to work. I like the garage door scenario, just what I was looking for!

**Comment by marcoskirsch** [comment]
I have gotten the code all cleaned up and working on the latest firmware. I tested on 1.5 but I think 1.4 will work (@rlust maybe you can confirm?)

Will upload later.

**Comment by marcoskirsch** [comment]
Uploaded, let me know if it's working for you. Thanks.
