### ISSUE TITLE
node_info in standalone mode

### ISSUE THREAD

**Issue by HEI-Luc** [marcoskirsch/nodemcu-httpserver#66]
Hi
Thank for all your work, it's usefull for me and my IOT project(s)

I want to use my nodeMCU in a nomad project, so it's configured in Station and Access Point, to be connected to the network of my house if available, or by the access point of the node itself.

I detect a problem with the node_info page, because when I'm without my home network, it's try to concat the nil IP in the string to send.

my quick patch is to check the wifi.sta.status in an IF statement before ask the IP

Thanks for all,
Luc

**Comment by marcoskirsch** [comment]
Sounds good! please submit a pull request. Thanks!

**Comment by marcoskirsch** [comment]
Fixed in https://github.com/marcoskirsch/nodemcu-httpserver/commit/54b6525805a80d8456ac95e2b307ad6b703deeeb by @HHHartmann
