### ISSUE TITLE
Basic HTTP Authentication is broken

### ISSUE THREAD

**Issue by marcoskirsch** [marcoskirsch/nodemcu-httpserver#96]
When I enable it in httpserver-conf.lua and try to go to any page, I get sent straight to the "401 - Unauthorized" error page.

This used to work, need to narrow it down.

**Comment by marcoskirsch** [comment]
Note to self: I suspect https://github.com/marcoskirsch/nodemcu-httpserver/pull/87
@HHHartmann do you typically test with Basic HTTP Authentication enabled?

It's getting late so I'll look more into this later.

**Comment by HHHartmann** [comment]
@marcoskirsch typically not, I will have a look into this
